Repository JonasMuehlmann/BIB_VPR, pull requests merged in 2021-08, with the labels that each got.

#259 Add method to retrieve replies of message
  Messenger/Messenger.Core.Tests.MSTest/Services/MessageServiceTest.cs
  Messenger/Messenger.Core/Services/MessageService.cs
Labels: status: review_phase

#277 Reaction bug
  Messenger/Messenger.Core/Services/AzureServiceBase.cs.example
  Messenger/Messenger.Core/Services/SignalRService.cs
  Messenger/Messenger/Helpers/Converters/CountToVisibilityConverter.cs
  Messenger/Messenger/Helpers/MessageHelpers/MessageBuilder.cs
  Messenger/Messenger/Messenger.csproj
  Messenger/Messenger/ViewModels/Controls/MessagesListControlViewModel.cs
  Messenger/Messenger/ViewModels/DataViewModels/MessageViewModel.cs
  Messenger/Messenger/Views/Pages/SettingsPage.xaml.cs
  Messenger/Messenger/Views/Subcontrols/MessageView.xaml
Labels: bug, frontend

#275 Role permission save bug
  Messenger/Messenger/Views/DialogBoxes/ManageRolesDialog.xaml
Labels: frontend, status: review_phase

#279 Add Setting Button in LandingPage
  Messenger/Messenger/Views/Pages/LandingPage.xaml
  Messenger/Messenger/Views/Pages/LandingPage.xaml.cs
Labels: frontend, status: review_phase

#281 Hotfix) EventProvider gets wrong parameter
  Messenger/Messenger/Helpers/BindingHelper.cs
  Messenger/Messenger/Helpers/CacheQuery.cs
  Messenger/Messenger/Helpers/ColorExtensions.cs
  Messenger/Messenger/Messenger.csproj
  Messenger/Messenger/Services/Providers/EventProvider.cs
Labels: bug, status: review_phase

#285 Fix delete message with replies
  Messenger/Messenger.Core.Tests.MSTest/Services/MessageServiceTest.cs
  Messenger/Messenger.Core/Services/MessageService.cs
Labels: status: review_phase

#287 Replace system colors with static colors
  Messenger/Messenger/App.xaml
  Messenger/Messenger/Helpers/CacheQuery.cs
  Messenger/Messenger/ViewModels/DataViewModels/TeamViewModel.cs
  Messenger/Messenger/Views/Controls/InboxControl.xaml
  Messenger/Messenger/Views/Controls/MembersListControl.xaml
  Messenger/Messenger/Views/Controls/MessagesListControl.xaml
  Messenger/Messenger/Views/Controls/SendMessageControl.xaml
  Messenger/Messenger/Views/Controls/UserSearchPanel.xaml
  Messenger/Messenger/Views/DialogBoxes/ChangeTeamDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/CreateChannelDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/CreateChatDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/CreateTeamDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/ManageMemberRolesDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/ManageRolesDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/OperationConfirmationDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/ResultConfirmationDialog.xaml
  Messenger/Messenger/Views/Pages/ChatNavPage.xaml
  Messenger/Messenger/Views/Pages/ChatPage.xaml
  Messenger/Messenger/Views/Pages/LandingPage.xaml
  Messenger/Messenger/Views/Pages/LogInPage.xaml
  Messenger/Messenger/Views/Pages/NotificationNavPage.xaml
  Messenger/Messenger/Views/Pages/SettingsPage.xaml
  Messenger/Messenger/Views/Pages/ShellPage.xaml
  Messenger/Messenger/Views/Pages/TeamManagePage.xaml
  Messenger/Messenger/Views/Pages/TeamNavPage.xaml
  Messenger/Messenger/Views/Subcontrols/ChatHeader.xaml
  Messenger/Messenger/Views/Subcontrols/MessageView.xaml
  Messenger/Messenger/Views/Subcontrols/OnLoading.xaml
  Messenger/Messenger/Views/Subcontrols/SideNavigation.xaml
Labels: frontend, status: review_phase

#289 Delete message
  Messenger/Messenger.Core/Services/MessengerService.cs
  Messenger/Messenger/ViewModels/Controls/MessagesListControlViewModel.cs
  Messenger/Messenger/Views/Subcontrols/MessageView.xaml
  Messenger/Messenger/Views/Subcontrols/MessageView.xaml.cs
  Messenger/Messenger/Views/Subcontrols/ReplyView.xaml
  Messenger/Messenger/Views/Subcontrols/ReplyView.xaml.cs
Labels: frontend, status: review_phase

#308 refactor: use env vars for connection strings
  .github/workflows/dotnet.yml
  .gitignore
  Messenger/Messenger.Core.Tests.MSTest/run_tests.sh
  Messenger/Messenger.Core/Services/AzureServiceBase.cs
Labels: status: review_phase

#282 Make Notifications more flexible
  Messenger/Messenger.Core.Tests.MSTest/Services/NotificationServiceTest.cs
  Messenger/Messenger.Core/Models/NotificationMute.cs
  Messenger/Messenger.Core/Services/NotificationService.cs
Labels: status: review_phase

#313 Fix invitation receive
  Messenger/Messenger/Services/Providers/EventProvider.cs
  Messenger/Messenger/ViewModels/Controls/MessagesListControlViewModel.cs
  Messenger/Messenger/ViewModels/DialogBoxes/ManageRolesDialogViewModel.cs
  Messenger/Messenger/ViewModels/Pages/ChatNavViewModel.cs
  Messenger/Messenger/ViewModels/Pages/ChatViewModel.cs
  Messenger/Messenger/ViewModels/Pages/TeamNavViewModel.cs
  Messenger/Messenger/Views/Pages/ChatNavPage.xaml.cs
  Messenger/Messenger/Views/Pages/LandingPage.xaml.cs
Labels: bug, status: review_phase

#201 (Suspended) Download `Attachment`s on click
  Messenger/Messenger.Core/Messenger - Backup.Core.csproj
  Messenger/Messenger.Core/Models/Message.cs
  Messenger/Messenger.Core/Models/UploadData.cs
  Messenger/Messenger.Core/Properties/launchSettings.json
  Messenger/Messenger.Core/Services/FileSharingService.cs
  Messenger/Messenger.Core/Services/MessengerService.cs
  Messenger/Messenger.Core/Services/SignalRService.cs
  Messenger/Messenger/Commands/Messenger/AttachFileCommand.cs
  Messenger/Messenger/Commands/Messenger/DownloadAttachmentCommand.cs
  Messenger/Messenger/Commands/Messenger/SendMessageCommand.cs
  Messenger/Messenger/Helpers/MessageHelpers/MessageBuilder.cs
  Messenger/Messenger/Messenger.csproj
  Messenger/Messenger/Models/Attachment.cs
  Messenger/Messenger/ViewModels/DataViewModels/MessageViewModel.cs
  Messenger/Messenger/Views/Controls/MessagesListControl.xaml
  Messenger/Messenger/Views/Subcontrols/MessageView.xaml
Labels: status: in development, discussion, frontend

#322 Implemented `Reload` for `Teams` and `Chats`
  Messenger/Messenger/Commands/Messenger/DownloadAttachmentCommand.cs
  Messenger/Messenger/Helpers/CacheQuery.cs
  Messenger/Messenger/Helpers/TeamHelpers/TeamManager.cs
  Messenger/Messenger/Services/Providers/StateProvider.cs
  Messenger/Messenger/ViewModels/Pages/ChatNavViewModel.cs
  Messenger/Messenger/ViewModels/Pages/TeamNavViewModel.cs
  Messenger/Messenger/Views/Pages/ChatNavPage.xaml
  Messenger/Messenger/Views/Pages/TeamNavPage.xaml
Labels: status: review_phase, binding

#324 Litle upload fix
  Messenger/Messenger/Commands/Messenger/AttachFileCommand.cs
Labels: status: review_phase

#320 change the username in the db
  Messenger/Messenger.Core/Services/MessengerService.cs
  Messenger/Messenger/Commands/UserData/UpdateUserNameCommand.cs
  Messenger/Messenger/Messenger.csproj
  Messenger/Messenger/ViewModels/Controls/MessagesListControlViewModel.cs
  Messenger/Messenger/ViewModels/Pages/SettingsViewModel.cs
  Messenger/Messenger/Views/Controls/MessagesListControl.xaml
  Messenger/Messenger/Views/Controls/MessagesListControl.xaml.cs
  Messenger/Messenger/Views/Pages/ChatNavPage.xaml
  Messenger/Messenger/Views/Pages/SettingsPage.xaml.cs
  Messenger/Messenger/Views/Pages/TeamNavPage.xaml
Labels: status: review_phase

#327 Display images
  .gitmodules
  Messenger/Messenger/Helpers/MessageHelpers/MessageBuilder.cs
  Messenger/Messenger/ViewModels/DataViewModels/MessageViewModel.cs
  Messenger/Messenger/Views/Subcontrols/MessageView.xaml
  Messenger/Messenger/Views/Subcontrols/MessageView.xaml.cs
Labels: status: review_phase

#328 Remove Team teamid bugs fixed
  Messenger/Messenger/Services/Providers/EventProvider.cs
  Messenger/Messenger/Views/Pages/TeamNavPage.xaml
Labels: status: review_phase

#329 chats not shown bug and delete bug
  Messenger/Messenger.Core/Services/MessengerService.cs
  Messenger/Messenger/ViewModels/Controls/MessagesListControlViewModel.cs
Labels: status: review_phase

#330 HOT FIX NULL EXCEPTION BEI NOTIFICATION VM
  Messenger/Messenger/ViewModels/DataViewModels/NotificationViewModel.cs
  Messenger/Messenger/Views/Controls/InboxControl.xaml
Labels: bug, status: review_phase

#316 Improve documentation coverage
  Messenger/Messenger.Console/Messenger.Console.csproj
  Messenger/Messenger.Console/Program.cs
  Messenger/Messenger.ConsoleMessenger/IMessengerApp.cs
  Messenger/Messenger.ConsoleMessenger/Messenger.ConsoleMessenger.csproj
  Messenger/Messenger.ConsoleMessenger/MessengerApp.cs
  Messenger/Messenger.ConsoleMessenger/Models/ChatMenuOption.cs
  Messenger/Messenger.ConsoleMessenger/Programs/ChatPage.cs
  Messenger/Messenger.ConsoleMessenger/Programs/HomePage.cs
  Messenger/Messenger.ConsoleMessenger/Programs/MessengerProgram.cs
  Messenger/Messenger.ConsoleMessenger/Runner.cs
  Messenger/Messenger.ConsoleMessenger/appsettings.json
  Messenger/Messenger.Core.Tests.MSTest/README.md
  Messenger/Messenger.Core.Tests.MSTest/Services/FileSharingServiceTest.cs
  Messenger/Messenger.Core/Helpers/GlobalLogger.cs
  Messenger/Messenger.Core/Helpers/Json.cs
  Messenger/Messenger.Core/Helpers/LoginResultType.cs
  Messenger/Messenger.Core/Helpers/Mapper.cs
  Messenger/Messenger.Core/Helpers/NotificationMessage.cs
  Messenger/Messenger.Core/Helpers/NotificationMessageBuilder.cs
  Messenger/Messenger.Core/Helpers/Singleton.cs
  Messenger/Messenger.Core/Helpers/SqlHelpers.cs
  Messenger/Messenger.Core/Helpers/StreamExtensions.cs
  Messenger/Messenger.Core/Messenger - Backup.Core.csproj
  Messenger/Messenger.Core/Models/Channel.cs
  Messenger/Messenger.Core/Models/Membership.cs
  Messenger/Messenger.Core/Models/Mention.cs
  Messenger/Messenger.Core/Models/MentionTarget.cs
  Messenger/Messenger.Core/Models/Mentionable.cs
  Messenger/Messenger.Core/Models/Message.cs
  Messenger/Messenger.Core/Models/Notification.cs
  Messenger/Messenger.Core/Models/NotificationMute.cs
  Messenger/Messenger.Core/Models/NotificationSource.cs
  Messenger/Messenger.Core/Models/NotificationType.cs
  Messenger/Messenger.Core/Models/Permissions.cs
  Messenger/Messenger.Core/Models/Reaction.cs
  Messenger/Messenger.Core/Models/SignalREventArgs.cs
  Messenger/Messenger.Core/Models/Team.cs
  Messenger/Messenger.Core/Models/TeamRole.cs
  Messenger/Messenger.Core/Models/UploadData.cs
  Messenger/Messenger.Core/Models/User.cs
  Messenger/Messenger.Core/Properties/launchSettings.json
  Messenger/Messenger.Core/README.md
  Messenger/Messenger.Core/Services/AzureServiceBase.cs.example
  Messenger/Messenger.Core/Services/ChannelService.cs
  Messenger/Messenger.Core/Services/FileSharingService.cs
  Messenger/Messenger.Core/Services/MentionService.cs
  Messenger/Messenger.Core/Services/MessageService.cs
  Messenger/Messenger.Core/Services/MessengerService.cs
  Messenger/Messenger.Core/Services/MicrosoftGraphService.cs
  Messenger/Messenger.Core/Services/NotificationService.cs
  Messenger/Messenger.Core/Services/PrivateChatService.cs
  Messenger/Messenger.Core/Services/SignalRService.cs
  Messenger/Messenger.Core/Services/TeamService.cs
  Messenger/Messenger.Core/Services/UserService.cs
  Messenger/Messenger.Core/readme.txt
  Messenger/Messenger.Tests.MSTest/README.md
  Messenger/README.md
Labels: status: in development, Backend implemented
