Repository JonasMuehlmann/BIB_VPR, pull requests merged in 2021-07, with the labels that each got.

#252 Refactor `ChatHubService`
  Messenger/Messenger/Controls/ChatControls/ChatHeader.xaml
  Messenger/Messenger/Controls/ChatControls/ChatHeader.xaml.cs
  Messenger/Messenger/Helpers/MessageBuilder.cs
  Messenger/Messenger/Helpers/MessageManager.cs
  Messenger/Messenger/Helpers/TeamBuilder.cs
  Messenger/Messenger/Helpers/TeamManager.cs
  Messenger/Messenger/Messenger.csproj
  Messenger/Messenger/Models/PrivateChat.cs
  Messenger/Messenger/Services/ChatHubService.cs
  Messenger/Messenger/TemplateSelectors/TeamDataTemplateSelector.cs
  Messenger/Messenger/ViewModels/DataViewModels/ChannelViewModel.cs
  Messenger/Messenger/ViewModels/DataViewModels/MessageViewModel.cs
  Messenger/Messenger/ViewModels/DataViewModels/TeamViewModel.cs
  Messenger/Messenger/ViewModels/MainPanels/ChatViewModel.cs
  Messenger/Messenger/ViewModels/MainPanels/TeamManageViewModel.cs
  Messenger/Messenger/ViewModels/NavigationPanels/ChatNavViewModel.cs
  Messenger/Messenger/ViewModels/NavigationPanels/TeamNavViewModel.cs
  Messenger/Messenger/ViewModels/ShellViewModel.cs
  Messenger/Messenger/Views/MainPanels/ChatPage.xaml
  Messenger/Messenger/Views/NavigationPanels/TeamNavPage.xaml
Labels: binding, status: review_phase

#230 Backend implementation of pinning message
  Messenger/Messenger.Core.Tests.MSTest/Services/ChannelTest.cs
  Messenger/Messenger.Core.Tests.MSTest/Services/Cleanup.cs
  Messenger/Messenger.Core.Tests.MSTest/Services/TeamServiceTest.cs
  Messenger/Messenger.Core.Tests.MSTest/Services/UserServiceTest.cs
  Messenger/Messenger.Core/Helpers/Mapper.cs
  Messenger/Messenger.Core/Helpers/SqlHelpers.cs
  Messenger/Messenger.Core/Models/Permissions.cs
  Messenger/Messenger.Core/Models/TeamRole.cs
  Messenger/Messenger.Core/Services/ChannelService.cs
  Messenger/Messenger.Core/Services/TeamService.cs
  README.md
  docs/MicrosoftTeams-image.png
  docs/MicrosoftTeams-image1.png
  docs/MicrosoftTeams-image2.png
Labels: status: review_phase

#254 Restyle `TeamNavPage` and `ChatNavPage` / `Message` bound to `Channel`s
  Messenger/Messenger/Controls/ChatControls/ChatHeader.xaml
  Messenger/Messenger/Controls/ChatControls/ChatHeader.xaml.cs
  Messenger/Messenger/Controls/Navigation/SideNavigation.xaml
  Messenger/Messenger/Helpers/MessageManager.cs
  Messenger/Messenger/Helpers/TeamBuilder.cs
  Messenger/Messenger/Models/PrivateChat.cs
  Messenger/Messenger/Services/ChatHubService.cs
  Messenger/Messenger/ViewModels/DataViewModels/ChannelViewModel.cs
  Messenger/Messenger/ViewModels/DataViewModels/TeamViewModel.cs
  Messenger/Messenger/ViewModels/MainPanels/ChatViewModel.cs
  Messenger/Messenger/ViewModels/NavigationPanels/ChatNavViewModel.cs
  Messenger/Messenger/ViewModels/NavigationPanels/TeamNavViewModel.cs
  Messenger/Messenger/Views/MainPanels/ChatPage.xaml
  Messenger/Messenger/Views/NavigationPanels/ChatNavPage.xaml
  Messenger/Messenger/Views/NavigationPanels/TeamNavPage.xaml
  Messenger/Messenger/Views/NavigationPanels/TeamNavPage.xaml.cs
  Messenger/Messenger/Views/ShellPage.xaml
Labels: binding, frontend, status: review_phase

#257 Roles
  Messenger/Messenger.Core.Tests.MSTest/Services/TeamServiceTest.cs
  Messenger/Messenger.Core/Helpers/Mapper.cs
  Messenger/Messenger.Core/Services/TeamService.cs
Labels: status: review_phase

#226 Backend implementation of mentions
  Messenger/Messenger.Core.Tests.MSTest/Services/MentionServiceTest.cs
  Messenger/Messenger.Core.Tests.MSTest/Services/MessageServiceTest.cs
  Messenger/Messenger.Core/Helpers/Mapper.cs
  Messenger/Messenger.Core/Models/Mention.cs
  Messenger/Messenger.Core/Models/MentionTargets.cs
  Messenger/Messenger.Core/Models/Mentionable.cs
  Messenger/Messenger.Core/Services/MentionService.cs
  Messenger/Messenger.Core/Services/TeamService.cs
Labels: status: review_phase

#210 Backend implementation of notifications
  Messenger/Messenger.Core.Tests.MSTest/Helpers/NotificationMessageBuildersTest.cs
  Messenger/Messenger.Core.Tests.MSTest/Services/Cleanup.cs
  Messenger/Messenger.Core.Tests.MSTest/Services/MentionServiceTest.cs
  Messenger/Messenger.Core.Tests.MSTest/Services/NotificationServiceTest.cs
  Messenger/Messenger.Core/Helpers/Mapper.cs
  Messenger/Messenger.Core/Helpers/NotificationMessage.cs
  Messenger/Messenger.Core/Helpers/NotificationMessageBuilder.cs
  Messenger/Messenger.Core/Helpers/SqlHelpers.cs
  Messenger/Messenger.Core/Models/Mention.cs
  Messenger/Messenger.Core/Models/MentionTarget.cs
  Messenger/Messenger.Core/Models/Notification.cs
  Messenger/Messenger.Core/Models/NotificationMute.cs
  Messenger/Messenger.Core/Models/NotificationSource.cs
  Messenger/Messenger.Core/Models/NotificationType.cs
  Messenger/Messenger.Core/Services/MentionService.cs
  Messenger/Messenger.Core/Services/MessageService.cs
  Messenger/Messenger.Core/Services/NotificationService.cs
Labels: has_dependency, status: review_phase

#260 UI & Binding for `TeamRole` and `Permissions`
  Messenger/Messenger.Core.Tests.MSTest/Services/MentionServiceTest.cs
  Messenger/Messenger.Core.Tests.MSTest/Services/TeamServiceTest.cs
  Messenger/Messenger.Core/Helpers/Mapper.cs
  Messenger/Messenger.Core/Models/TeamRole.cs
  Messenger/Messenger.Core/Services/MessengerService.cs
  Messenger/Messenger.Core/Services/SignalRService.cs
  Messenger/Messenger.Core/Services/TeamService.cs
  Messenger/Messenger.SignalR/ChatHub.cs
  Messenger/Messenger/App.xaml.cs
  Messenger/Messenger/Commands/TeamManage/AssignTeamRoleCommand.cs
  Messenger/Messenger/Commands/TeamManage/CreateTeamCommand.cs
  Messenger/Messenger/Commands/TeamManage/CreateTeamRoleCommand.cs
  Messenger/Messenger/Commands/TeamManage/RemoveChannelCommand.cs
  Messenger/Messenger/Commands/TeamManage/RemoveTeamRoleCommand.cs
  Messenger/Messenger/Commands/TeamManage/RemoveUserCommand.cs
  Messenger/Messenger/Commands/TeamManage/RevokePermissionCommand.cs
  Messenger/Messenger/Commands/TeamManage/UnassignTeamRoleCommand.cs
  Messenger/Messenger/Commands/TeamManage/UpdateTeamRoleCommand.cs
  Messenger/Messenger/Controls/ChatControls/ChatHeader.xaml
  Messenger/Messenger/Controls/ChatControls/ChatHeader.xaml.cs
  Messenger/Messenger/Controls/ManageControls/MembersListControl.xaml
  Messenger/Messenger/Controls/ManageControls/MembersListControl.xaml.cs
  Messenger/Messenger/Controls/Navigation/SideNavigation.xaml
  Messenger/Messenger/Controls/Navigation/SideNavigation.xaml.cs
  Messenger/Messenger/Controls/Shared/RoleTag.xaml
  Messenger/Messenger/Controls/Shared/RoleTag.xaml.cs
  Messenger/Messenger/Helpers/CacheQuery.cs
  Messenger/Messenger/Helpers/ColorHelper.cs
  Messenger/Messenger/Helpers/Converters/ColorToHexCodeConverter.cs
  Messenger/Messenger/Helpers/Converters/NullToVisibilityConverter.cs
  Messenger/Messenger/Helpers/TeamHelpers/TeamBuilder.cs
  Messenger/Messenger/Helpers/TeamHelpers/TeamManager.cs
  Messenger/Messenger/Messenger.csproj
  Messenger/Messenger/Services/NavigationService.cs
  Messenger/Messenger/Services/Providers/EventProvider.cs
  Messenger/Messenger/Services/Providers/StateProvider.cs
  Messenger/Messenger/Services/UserDataService.cs
  Messenger/Messenger/ViewModels/Controls/MembersListControlViewModel.cs
  Messenger/Messenger/ViewModels/DataViewModels/MemberViewModel.cs
  Messenger/Messenger/ViewModels/DataViewModels/TeamRoleViewModel.cs
  Messenger/Messenger/ViewModels/DialogBoxes/ManageMemberRolesDialogViewModel.cs
  Messenger/Messenger/ViewModels/DialogBoxes/ManageRolesDialogViewModel.cs
  Messenger/Messenger/ViewModels/MainPanels/SettingsViewModel.cs
  Messenger/Messenger/ViewModels/MainPanels/TeamManageViewModel.cs
  Messenger/Messenger/ViewModels/NavigationPanels/TeamNavViewModel.cs
  Messenger/Messenger/Views/DialogBoxes/ManageMemberRolesDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/ManageMemberRolesDialog.xaml.cs
  Messenger/Messenger/Views/DialogBoxes/ManageRolesDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/ManageRolesDialog.xaml.cs
  Messenger/Messenger/Views/DialogBoxes/OperationConfirmationDialog.xaml
  Messenger/Messenger/Views/DialogBoxes/OperationConfirmationDialog.xaml.cs
  Messenger/Messenger/Views/MainPanels/SettingsPage.xaml
  Messenger/Messenger/Views/MainPanels/TeamManagePage.xaml
  Messenger/Messenger/Views/NavigationPanels/TeamNavPage.xaml
  Messenger/Messenger/Views/ShellPage.xaml
Labels: binding, frontend, status: review_phase
